{% set name = "torch-complex" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torch_complex-{{ version }}.tar.gz
  sha256: 4153fd6b24a0bad689e6f193bfbd00f38283b1890d808bef684ddc6d1f63fd3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - pytorch

test:
  imports:
    - torch_complex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kamo-naoyuki/pytorch_complex
  summary: A fugacious python class for PyTorch-ComplexTensor
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wietsedv
